### ISSUE TITLE
[BUG] Super stream not updating

### ISSUE THREAD

**Issue by breaking-loss** [recloudstream/cloudstream-extensions#20]
I use the super stream plugin and the TV shows and movies are not working for me . It shows the information of new ep from IMDb but the app displays "link not found" .
Eg : S 6ep 6 op rick and and Morty is missing ,chainsaw man ep 1 is missing , gangs of wasseypur part 2 is missing .I can't find the website of super stream so can't report this . Is the problem with the extension or is the website not updating .

**Comment by breaking-loss** [comment]
My bad I didn't know that the app got shut down again . What is wrong with them . Does anyone kno wthe links of the English extension . I don't want to join discord .

**Comment by C10udburst** [comment]
> My bad I didn't know that the app got shut down again . What is wrong with them . Does anyone kno wthe links of the English extension . I don't want to join discord .

https://cloudflare-ipfs.com/ipns/cloudstream.cf/ here

**Comment by breaking-loss** [comment]
Thank you . If you dont mind is cloudstream.cf original or a copycat
