### ISSUE TITLE
tenshi.moe has moved to marin.moe

### ISSUE THREAD

**Issue by rollingmoai** [recloudstream/cloudstream-extensions#34]
https://tenshi.moe/ has closed, redirecting to their new site https://marin.moe/. Please fix:
![image](https://user-images.githubusercontent.com/75471378/212290434-d39c862c-fa4f-4542-9f71-eb25cf66de5e.png)

**Comment by rollingmoai** [comment]
@LagradOst still doesn't work

**Comment by venkat2305** [comment]
It's not working. Please reopen this issue.

**Comment by venkat2305** [comment]
Marin.moe has ddos protection for some users. Please look into ths.
