### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by Light7654** [recloudstream/cloudstream-extensions#42]
Dark Theme (Dark blue theme)
![iPhone 13 mini - 1](https://user-images.githubusercontent.com/87866912/225442518-fd669983-d302-4d3d-8636-ec02867f07af.png)
Light blue theme
![iPhone 13 mini - 2](https://user-images.githubusercontent.com/87866912/225442555-d081633e-d953-4bf0-bafb-012bc6e88d76.png)
Light Theme
![iPhone 13 mini - 3](https://user-images.githubusercontent.com/87866912/225442573-3afc4a34-2e93-421b-ace7-8d2edca8efa8.png)

**Comment by LagradOst** [comment]
duplicate
